DROP TABLE TMP_MA_PERSONAS;
DROP TABLE MA_PERSONAS;

-- SENTENCIA DE CREACION DE LA TABLA - ESQUEMA LANDING
CREATE TABLE TMP_MA_PERSONAS(
NumDoc VARCHAR2(8),
DigVer VARCHAR2(1),
GrpVot VARCHAR2(15),
Ubigeo VARCHAR2(6),
ApPaterno VARCHAR2(100),
ApMaterno VARCHAR2(100),
Nombres VARCHAR2(100),
FecNac VARCHAR2(8),
Sexo VARCHAR2(2)
)

select * from TMP_MA_PERSONAS

-- SENTENCIA DE CREACION DE LA TABLA - ESQUEMA OPERACIONAL
drop table MA_PERSONAS;

CREATE TABLE MA_PERSONAS(
MPE_NUMDOC CHAR(8),
MPE_DIGVER CHAR(1),
MPE_GRPVOT VARCHAR(10),
MPE_UBIGEO CHAR(6),
MPE_FECNAC DATE,
MPE_SEXO CHAR(1),
MPE_EDAD number 
)

-- CARGANDO TABLA OPERACIONAL CON DATOS DE LA TABLA LANDING - ESQUEMA OPERACIONAL 
-- NO SE CONSIDERA 1224 REGISTROS CON DATO 'PARCHE EQX" EN GrpVot
-- NO SE CONSIDERA ApPaterno,ApMaterno, Nombres CONTIENE SOLO DATOS NN

INSERT INTO MA_PERSONAS 
(SELECT TRIM(NumDoc), TRIM(DigVer), TRIM(GrpVot), TRIM(Ubigeo), TO_DATE((SUBSTR(FecNac,7,2)||'/'||SUBSTR(FecNac,5,2)||'/'||SUBSTR(FecNac,1,4)),
'DD/MM/YYYY'), TRIM(Sexo) ,
FLOOR(MONTHS_BETWEEN( TRUNC(SYSDATE), TO_DATE(FECNAC,'YYYYMMDD')) / 12) EDAD

FROM tmp_ma_personas WHERE GrpVot<>'PARCHE EQX')

select * from ma_personas

SELECT a.*,
sysdate fechaHoy,
EXTRACT(YEAR FROM sysdate) - EXTRACT(YEAR FROM MPE_FECNAC) edad
FROM MA_PERSONAS a ; 


SELECT a.*, TRUNC( ( TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDD')) -  TO_NUMBER(TO_CHAR(MPE_FECNAC,'YYYYMMDD') ) ) / 10000) AS Edad
FROM MA_PERSONAS a ;

SELECT a.*,  ( TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDD')) -  TO_NUMBER(TO_CHAR(MPE_FECNAC,'YYYYMMDD') ) ) AS Edad
FROM MA_PERSONAS a ;

SELECT a.*,( TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDD')) -  TO_NUMBER(TO_CHAR(MPE_FECNAC,'YYYYMMDD') ) ) / 10000 AS Edad_decimal,
 TRUNC( ( TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDD')) -  TO_NUMBER(TO_CHAR(MPE_FECNAC,'YYYYMMDD') ) ) / 10000) AS Edad
FROM MA_PERSONAS a 
where a.MPE_NUMDOC='15336570';

--REVISARLO
SELECT a.*,( TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDD')) -  TO_NUMBER(TO_CHAR(fecnac,'YYYYMMDD') ) ) / 10000 AS Edad_decimal,
 TRUNC( ( TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDD')) -  TO_NUMBER(TO_CHAR(fecnac,'YYYYMMDD') ) ) / 10000) AS Edad
FROM tmp_ma_personas a 
where a.NUMDOC='15336570'


-- VISUALIZAR LA INFORMACIÓN 
SELECT * FROM TMP_MA_PERSONAS;
SELECT * FROM MA_PERSONAS;


--- CONTAR REGISTROS
SELECT COUNT(*) FROM TMP_MA_PERSONAS;
-- 28525
SELECT COUNT(*) FROM MA_PERSONAS;
-- 27301 DEPURADO 

