-- SENTENCIA ELIMINAR TABLA
DROP TABLE TMP_MA_UBIGEO;
DROP TABLE MA_UBIGEO;

-- SENTENCIA DE CREACION DE LA TABLA - ESQUEMA LANDING
CREATE TABLE TMP_MA_UBIGEO(
Ubigeo VARCHAR2(6),
Departamento VARCHAR2(15),
Provincia VARCHAR2(30),
Distrito VARCHAR2(36),
Codigo VARCHAR2(6),
distrito_det VARCHAR2(30),
FlgZona VARCHAR2(4),
CENTROSNEGOCIO VARCHAR2(14),
FLGPROVCENTROSNEGOCIO VARCHAR2(2),
distrito_agg VARCHAR2(30),
FlgCiudad VARCHAR2(2)
)

select * from TMP_MA_UBIGEO 

-- SENTENCIA DE CREACION DE LA TABLA - ESQUEMA OPERACIONAL 
CREATE TABLE MA_UBIGEO(
MUB_UBIGEO CHAR(6),
MUB_DEPARTAMENTO VARCHAR2(13),
MUB_PROVINCIA VARCHAR2(25),
MUB_DISTRITO VARCHAR2(36),
MUB_FLGZONA VARCHAR2(4),
MUB_FLGCIUDAD CHAR(1)
)

-- CARGANDO TABLA OPERACIONAL CON DATOS DE LA TABLA LANDING - ESQUEMA OPERACIONAL 

INSERT INTO MA_UBIGEO (SELECT TRIM(ubigeo), TRIM(departamento), TRIM(provincia), TRIM(distrito), TRIM(flgzona), TRIM(flgciudad) FROM tmp_ma_ubigeo)

-- VISUALIZAR LA INFORMACIÓN 
SELECT * FROM TMP_MA_UBIGEO;
SELECT * FROM MA_UBIGEO;


--- CONTAR REGISTROS
SELECT COUNT(*) FROM TMP_MA_UBIGEO;
SELECT COUNT(*) FROM MA_UBIGEO;
-- 1834